#!/bin/sh
SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
NETNAME="$1"
GAME="$2"

function colortext() {
	echo -ne "\x1b[3$1m$2\x1b[0m"
}

function message() {
	echo -ne "[$(colortext $1 "$2")] $3\n"
}

function msg_info() {
	message 4 "INFO" "$@"
}

function msg_warn() {
	message 3 "WARN" "$@"
}

function msg_err() {
	message 1 "FAIL" "$@"
}

function msg_ok() {
	message 2 " OK " "$@"
}

function fail() {
	msg_err "$@"
	exit 1
}

function usage() {
	msg_info "Usage: $(basename "$0") <zerotier-network> <game>"
}

if ! [ -x "$(command -v playonlinux)" ]; then
	fail "Please install playonlinux"
fi

if ! [ -x "$(command -v zerotier-cli)" ]; then
	fail "Please install zerotier-one"
fi

if [ -z "$NETNAME" ]; then
	msg_err "Missing network name"
	usage
	exit 1
fi

if [ -z "$GAME" ]; then
	msg_err "Missing game name"
	usage
	exit 1
fi

# Logo
cat << 'EOF'

\\\\ 
 \..\-\ 
  \....\-\ 
   \.......\-\
    \.........\-\
     \-----------\              _            _
      \ ___        \         __| |_  __ _ __| |
      / <O>    _    |       / _| ' \/ _` / _` |
     /          |   |       \__|_||_\__,_\__,_|
    /          _/  /
   (__ ~          |                       _
     /     \     /|       __ _ __ _ _ __ (_)_ _  __ _
    (__,    |   / |      / _` / _` | '  \| | ' \/ _` |
    (__    /   /  |      \__, \__,_|_|_|_|_|_||_\__, |
   ___/       /   |      |___/                  |___/ 
  /          /    |
  \---------/  /  |
         \    |   |
         |        |
         
EOF

STATUS="$(sudo zerotier-cli listnetworks | cut -d ' ' -f 3-)"
NETINFO="$(echo "$STATUS" | grep -E "^$NETNAME")"

if [ -z "$NETINFO" ]; then
	msg_err "Unknown network name '$NETNAME'"
	msg_info "Hint: Are you sure that zerotier-one is running? You can start it with \`sudo systemctl start zerotier-one\`"
	exit 1
fi

# Look for OK PUBLIC/PRIVATE
if ! echo "$NETINFO" | grep -E 'OK\s+(PUBLIC|PRIVATE)' > /dev/null; then
	fail "Access denied to the network '$NETNAME'"
fi

# Extract interface name
IFACE="$(echo "$NETINFO" | cut -d ' ' -f 6)"
if [ -z "$IFACE" ]; then
	fail "Failed to determine interface name for '$NETNAME'"
fi

msg_info "Network '$NETNAME' is assigned to interface '$IFACE'"
msg_ok "The Chad Gaming Launcher has done its job."

"$SCRIPTDIR/easyjailif" $IFACE << EOF
playonlinux --run "$GAME"
EOF
