#!/bin/sh
SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
NAMESPACE="gigachad_$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 8)"
IFACE="$1"
GAME="$2"

function colortext() {
	echo -ne "\x1b[3$1m$2\x1b[0m"
}

function message() {
	echo -ne "[$(colortext $1 "$2")] $3\n"
}

function msg_info() {
	message 4 "INFO" "$@"
}

function msg_warn() {
	message 3 "WARN" "$@"
}

function msg_err() {
	message 1 "FAIL" "$@"
}

function msg_ok() {
	message 2 " OK " "$@"
}

function fail() {
	msg_err "$@"
	exit 1
}

function usage() {
	msg_info "Usage: $(basename "$0") <interface> <game>"
}

if ! [ -x "$(command -v playonlinux)" ]; then
	fail "Please install playonlinux"
fi

if ! [ -x "$(command -v zerotier-cli)" ]; then
	fail "Please install zerotier-one"
fi

if [ -z "$IFACE" ]; then
	msg_err "Missing interface name"
	usage
	exit 1
fi

if [ -z "$GAME" ]; then
	msg_err "Missing game name"
	usage
	exit 1
fi

# Logo
cat << 'EOF'

\\\\ 
 \..\-\ 
  \....\-\ 
   \.......\-\
    \.........\-\
     \-----------\              _            _
      \ ___        \         __| |_  __ _ __| |
      / <O>    _    |       / _| ' \/ _` / _` |
     /          |   |       \__|_||_\__,_\__,_|
    /          _/  /
   (__ ~          |                       _
     /     \     /|       __ _ __ _ _ __ (_)_ _  __ _
    (__,    |   / |      / _` / _` | '  \| | ' \/ _` |
    (__    /   /  |      \__, \__,_|_|_|_|_|_||_\__, |
   ___/       /   |      |___/                  |___/ 
  /          /    |
  \---------/  /  |
         \    |   |
         |        |
         
EOF


"$SCRIPTDIR/easyjailif" $IFACE << EOF
playonlinux --run "$GAME"
EOF
